
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-02-14T18:51:25-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "e980b0d6679b4a832c235c16b8af48af1536cc61",
 "version": "0.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
